# Generated by Django 3.2.4 on 2021-07-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelThree',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelTwo',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
