# Generated by Django 3.2.4 on 2021-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogtitle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogtext',
            new_name='thetext',
        ),
    ]
